<template>
  <section class="teacher-page" data-testid="teacher-diagnosis-case-page">
    <div v-if="store.diagnosisState === 'LOADING' || store.diagnosisState === 'INITIAL'" class="state-panel">正在加载诊断证据...</div>
    <div v-else-if="store.diagnosisState !== 'READY' || !store.diagnosis" class="state-panel state-panel--error"><h1>{{ store.diagnosisState === 'NOT_FOUND' ? '诊断案例不可用' : '诊断证据暂时不可用' }}</h1><p>{{ store.error ?? '当前 case 没有可读取的真实证据。' }}</p><button type="button" @click="load">重新加载</button></div>
    <template v-else><header class="page-heading"><div><p class="eyebrow">Diagnosis evidence</p><h1>诊断案例</h1><p>{{ diagnosis.studentName }} · {{ diagnosis.courseName }} · {{ diagnosis.className }}</p></div><button class="outline-button" type="button" @click="router.push('/teacher/workbench')">返回工作台</button></header><section class="diagnosis-banner"><div><span>关注等级</span><strong :class="`severity severity--${diagnosis.severity.toLowerCase()}`">{{ severityLabel(diagnosis.severity) }}</strong></div><div><span>诊断置信度</span><strong>{{ percent(diagnosis.confidence) }}</strong></div></section><section class="panel hypothesis-panel"><span class="eyebrow">Primary hypothesis</span><h2>{{ diagnosis.primaryHypothesis }}</h2><p>以下内容来自当前 Read Model 中的学习状态与答题事实。</p></section><div class="evidence-grid"><section class="panel"><header class="panel-heading"><div><span class="eyebrow">Supporting evidence</span><h2>支持证据</h2></div><span class="panel-count">{{ diagnosis.evidence.length }} 条</span></header><ul v-if="diagnosis.evidence.length"><li v-for="item in diagnosis.evidence" :key="item">{{ item }}</li></ul><p v-else class="empty-inline">暂无支持证据</p></section><section class="panel"><header class="panel-heading"><div><span class="eyebrow">Counter evidence</span><h2>反向证据</h2></div><span class="panel-count">{{ diagnosis.counterEvidence.length }} 条</span></header><ul v-if="diagnosis.counterEvidence.length"><li v-for="item in diagnosis.counterEvidence" :key="item">{{ item }}</li></ul><p v-else class="empty-inline">暂无反向证据</p></section></div></template>
  </section>
</template>
<script setup lang="ts">
import { computed, onMounted } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { useTeacherStore } from '@/stores/teacherStore'
const route=useRoute(); const router=useRouter(); const store=useTeacherStore(); const diagnosis=computed(()=>store.diagnosis!); const percent=(v:number)=>`${Math.round(v*100)}%`; const severityLabel=(v:string)=>({HIGH:'高关注',MEDIUM:'中关注',LOW:'低关注'}[v]??'待评估'); async function load(){await store.loadDiagnosis(String(route.params.caseId),true)} onMounted(()=>void load())
</script>
<style scoped>
.teacher-page{display:grid;gap:16px;min-width:0;color:#172238}.page-heading{display:flex;justify-content:space-between;gap:18px;align-items:end}.page-heading h1{margin:4px 0;color:#172a4b;font-size:28px}.page-heading p:last-child{margin:0;color:#6e7c92;font-size:13px}.eyebrow{margin:0;color:#2563eb;font-size:11px;font-weight:800}.outline-button{min-height:38px;padding:0 14px;border:1px solid #b9cdf0;border-radius:7px;color:#2563eb;background:#fff;cursor:pointer;font-size:13px}.diagnosis-banner{display:grid;grid-template-columns:1fr 1fr;gap:1px;border:1px solid #dfe7f2;border-radius:8px;background:#dfe7f2;overflow:hidden}.diagnosis-banner div{display:grid;gap:6px;padding:15px 17px;background:#fff}.diagnosis-banner span{color:#8290a3;font-size:11px}.diagnosis-banner strong{color:#245fc9;font-size:20px}.severity{display:inline-block;width:max-content;padding:4px 8px;border-radius:5px;font-size:13px}.severity--high{color:#b24a42!important;background:#fff0ef}.severity--medium{color:#a56a13!important;background:#fff5e4}.severity--low{color:#258052!important;background:#eaf8ef}.panel{min-width:0;padding:18px;border:1px solid #dfe7f2;border-radius:8px;background:#fff;box-shadow:0 5px 18px rgb(37 61 99 / 6%)}.hypothesis-panel h2{margin:7px 0 4px;color:#1d3d70;font-size:20px}.hypothesis-panel p{margin:0;color:#708098;font-size:12px}.evidence-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.panel-heading{display:flex;justify-content:space-between;gap:10px;padding-bottom:11px;border-bottom:1px solid #edf0f5}.panel-heading h2{margin:3px 0 0;color:#1d335e;font-size:16px}.panel-count{color:#8b9ab0;font-size:11px}.panel ul{display:grid;gap:9px;margin:14px 0 0;padding-left:18px;color:#4b607d;font-size:13px;line-height:1.6}.empty-inline{margin:0;padding:20px 0;color:#93a0b2;font-size:12px;text-align:center}.state-panel{display:grid;min-height:390px;place-items:center;align-content:center;gap:10px;padding:28px;border:1px solid #dfe7f2;border-radius:8px;background:#fff;text-align:center}.state-panel h1,.state-panel p{margin:0}.state-panel p{color:#6e7c92;font-size:13px}.state-panel button{min-height:36px;padding:0 14px;border:0;border-radius:7px;color:#fff;background:#2f6de9;cursor:pointer}.state-panel--error{color:#a43c38}@media(max-width:640px){.page-heading{align-items:start;flex-direction:column}.evidence-grid,.diagnosis-banner{grid-template-columns:1fr}.panel{padding:14px}}
</style>
